### ISSUE TITLE
Changing skin cause all player skin changed

### ISSUE THREAD

**Issue by ThisTNTSquid** [TheDuckCow/MCprep#10]
I spawned in 2 player charactors. When i select one charactor and change its skin, all player charactors' skin changed to the skin I selected. This made me impossible to have multiple charactors at the same scene!

**Comment by ThisTNTSquid** [comment]
The simple fix is get another rig :)

**Comment by TheDuckCow** [comment]
Thanks for the post. The reason is due tot he fact that it modifies the material, doesn't create a new issue. Depending on the use case, that may be a good or a bad thing. So, as far as I'm concerned, the right approach would be to expose to the use a checkbox option to "Assign to new material" or not. Some intelligence would need to be made around it assigning a new duplicate material to only the select rig, which may be tricky but could be done assuming parenting and/or active selection is valid.

**Comment by ThisTNTSquid** [comment]
Oh, thanks for your reply, but I will rather get an individual rig for animating, cuz that one is relatively easier to use and the outcome is better. But anyways, thanks for responding this
