### ISSUE TITLE
Fire won't animate

### ISSUE THREAD

**Issue by FoxcatgamingZ** [TheDuckCow/MCprep#100]
So I opened a nether world into blender using mineways and then using mcprep I attempted to make the lava and fire animated. the lava changed but the uv wasn't scaled or mapped correctly and then when I tried the fire it did change the material however it was not animated and didn't change the uv.
<img width="899" alt="report" src="https://user-images.githubusercontent.com/52290347/71385782-c8177200-25a6-11ea-911e-270a52d2c695.PNG">

it looks the same before and after and won't change (also this is in eevee render)

**Comment by TheDuckCow** [comment]
Hi there, thanks for sharing. This is because animated textures are not yet properly supported using Mineways, but I am working on it. In the meantime, you can try meshswapping on fire elements to get a fire material that is animated, but you will still need to manually go in an scale all of the UVs up (part of the issue with getting support ready).

**Comment by TheDuckCow** [comment]
Closing this issue as a near-term update is enabling support for mineways.
