### ISSUE TITLE
 Water glitch

### ISSUE THREAD

**Issue by davemaste** [TheDuckCow/MCprep#113]
I have Blender 2.79 and when I import a Minecraft world into blender and it contains water, the water is magenta in materials mode. The map is in 1.12.2, and the textures are somehow from 1.15

**Comment by TheDuckCow** [comment]
Hi, what did you use to export the world, jmc2obj or Mineways? How does the world look when you immediately pull it in (before using any MCprep features)? Screenshots would help. If the textures are from 1.15, it's likely because that's what the version of jmc2obj or Mineways you are running is prepackaged to use.

**Comment by TheDuckCow** [comment]
Just following up here, does the issue persist? If you need different textures that are not 1.15, then you should consider setting that as a resource pack at the time of exporting (ie in the Mineways or jmc2obj interface).

**Comment by TheDuckCow** [comment]
Closing in the meantime - let me know if still an issue.
