### ISSUE TITLE
Blender 2.8 Addon installation issues

### ISSUE THREAD

**Issue by RushilKoul** [TheDuckCow/MCprep#119]
Whenever I try to install the addon it is not enabled by default; and when I try to enable it it just shows this:
![Screenshot 2020-05-06 at 4 57 25 PM](https://user-images.githubusercontent.com/64902289/81171841-c204b980-8fba-11ea-936d-328a3ba36b5f.png)

help

**Comment by TheDuckCow** [comment]
Thanks for sharing this, a long standing bug that I think I finally have a solve for. Please wait for the next update which should be in a few days, I'll comment back when it is out.

**Comment by TheDuckCow** [comment]
Sorry for the delay, but the latest release should hopefully address this. Can you let me know if installing MCprep works now, with v3.2.3.1?

**Comment by RushilKoul** [comment]
> Sorry for the delay, but the latest release should hopefully address this. Can you let me know if installing MCprep works now, with v3.2.3.1?

yeah it does, thank you!

**Comment by TheDuckCow** [comment]
Thanks for sharing! And great to hear, closing this issue in the meantime - really happy to hear I found the fix here.

For the record, the issue was that - while locally I had __init__.py files in the subfolders for mobs, it was not actually committed to the repo. It's interesting that installing still worked fine for the majority of users, while specific users could not pass the issue, but not a concern for me today.
