### ISSUE TITLE
How do you import slim skins into the rig properly? And how do you shrink the size of the eye of the normal player mob?

### ISSUE THREAD

**Issue by ImSloke** [TheDuckCow/MCprep#130]
Probably a dumb question. Sorry...

**Comment by TheDuckCow** [comment]
Hi there,

You should be able to import slim skins the same as any other - MCprep doesn't treat it differently, however what ultimately matters is how the UV layout is treated on the models themselves.

For instance, you will want to spawn in the Alex rig for instance which is setup with skinny arms. If using another model which doesn't have the setup for "skinny geometry", you might need to make some local edits after importing.

For shrinking the eyes: when you say "normal player mob", you mean the one exactly highlighted below?
![player](https://user-images.githubusercontent.com/2958461/83977776-1f00d180-a8d1-11ea-9dbf-59641358fb4e.png)

If so, you can to a certain degree use the eye controls that are directly around the eyes themselves. Otherwise, again, you'll want to go into edit mode on the head model and move the vertices around to the shape you want. 

Hope this helps!

**Comment by ImSloke** [comment]
Wow these responses from an INDIVIDUAL are like a bajillion times better
and more informative than ANY cooperation I know. Keep up the good work!
And yes your solutions worked btw. :)

**Comment by TheDuckCow** [comment]
Awesome, glad to hear it - and happy to help. Don't be shy to share back what you create!
