### ISSUE TITLE
Mesh Swap needs to be non-case-sensitive.

### ISSUE THREAD

**Issue by Sam54123** [TheDuckCow/MCprep#152]
I'm unsure of exactly when this happened, but Mineways now exports materials with upper-case names. This breaks Mesh Swap because Mesh Swap expects materials with lower-case names, and it's annoying to have to manually change all of them.

**Comment by TheDuckCow** [comment]
Thanks for sharing, I'll work on generalizing this. For my investigations, can you share your Mineways export settings (e.g. using tiles or combined textures, and are sub material names selected?)

**Comment by Sam54123** [comment]
Here you go:
![Capture](https://user-images.githubusercontent.com/34262244/92542799-a0cd0780-f1fe-11ea-99cb-b5dfbba15050.PNG)

**Comment by TheDuckCow** [comment]
Perfect, thanks. For the record, if you tried selecting the "export tiles for textures to directory" setting, MeshSwap likely would work better. And even if you don't want to do that, will also help if you tick the box "split by block type". Though I recognize that doesn't totally fix your issue here (hence I marked as a bug), generally both of these settings will make meshswap (and animate textures, and swap texture-pack) work much better.

**Comment by TheDuckCow** [comment]
Marking as completed, as I have validated this works in my dev branch - will be included in the v3.2.4 release!
