### ISSUE TITLE
Grayscale Grass, Ferns and Greenery

### ISSUE THREAD

**Issue by KittenCat1080ti** [TheDuckCow/MCprep#157]
As the title says,  fern, and grass textures are grey after prepping materials. Oddly enough, leaf textures are not grey. I know you added a check for this in 3.2.1 I think. But it is not working apparently. I am using the Default Texture pack, mc2obj for importing. I am using the latest version of mcprep. It is probably just me being dumb but any help is appreciated. 

Thanks :)

**Comment by TheDuckCow** [comment]
Hi there - make sure you enter material mode or rendered mode, then it should work. 

The reason the "solid mode" will still appear grayscale is because blender, in solid mode with texture preview, simply directly shows the raw texture itself, and not the other shading things MCprep does to give it color back (which should appear in material or rendered mode). Let me know if still having trouble!

**Comment by KittenCat1080ti** [comment]
I was in render Mode, everything other then the grass and ferns had color. I reinstalled MCprep to get the default settings. now the grass has color, but not the leaves. still that way in renders too. Another problem: There is a Massive Carrot after mesh swapping and several blocks are missing. 

Is there a reason that there are missing blocks after meshswap? (See second Image)

![image](https://user-images.githubusercontent.com/71938947/94348448-650dac80-000a-11eb-948d-4926ee839156.png)
![image](https://user-images.githubusercontent.com/71938947/94348477-8ff80080-000a-11eb-8609-2662c6e82594.png)


At least the grass is back to normal though


Thanks for the fast reply though :)

**Comment by TheDuckCow** [comment]
Okay, I'm going to hope this is fixed in the upcoming release (v3.2.4) where I use a less strict test of grayscale or not. It doesn't hurt to try prepping one more time if you can (be sure those objects are selected first), but failing that, go into nodes and of the materials that should be green and select and press m to unmute this node, and give it a desirable color. 

![Screen Shot 2020-09-26 at 3 15 06 PM](https://user-images.githubusercontent.com/2958461/94348544-2c220780-000b-11eb-8d3a-1a91aaa11073.png)

For the meshswap issues, my guess is inconsistent scale - make sure you export objects from Mineways or jmc2obj with a height of 1m, not 100cm.

**Comment by KittenCat1080ti** [comment]
Thanks, I will try this.

 Again, thanks for such a fast response

**Comment by KittenCat1080ti** [comment]
Also, The stone brick meshswap is correctly scaled, but does not fill the gaps in between blocks leaving holes in between. showing the void. Also the part about the missing blocks. I re-did the export and double checked that map scale was at 1.0 

sorry for taking up so much of your time. and thank you. I am going to close this issue and open another specifically about the meshswap issues to keep your repository cleaner.
