### ISSUE TITLE
Blocks missing textures and materials

### ISSUE THREAD

**Issue by SmanCam** [TheDuckCow/MCprep#173]
I used this for spawning lanterns and campfires into my scene ![I used this](https://user-images.githubusercontent.com/69922601/98481995-94652b00-21fe-11eb-8c00-c5348a168e7f.PNG)

they were fine but after some restarts, they are missing textures and materials I can't see them in note editor anywhere. But when rendering they are there. So that won't be the problem but I'm sharing this .blend file on my network to another PC to render but it can't see it even when rendering.
![MissingTextures](https://user-images.githubusercontent.com/69922601/98482081-1ce3cb80-21ff-11eb-85fe-316240883b26.PNG)

![fbnjuabsfia](https://user-images.githubusercontent.com/69922601/98482103-46045c00-21ff-11eb-8034-472fc50ba6ff.PNG)

**Comment by TheDuckCow** [comment]
Hi there, the issue is likely that they reference textures that are housed inside the MCprep addon folder. To fix this, select campfire and lantern, then go to the MCprep tab, "World Imports" panel, and click on Advanced. Then hit the "Animate textures" button, and with the popup, be sure to select "next to this blend file" instead of next to source images. 

Then, when sending to another computer, be sure to send both the blend file as well as the textures folder next to it (you can't pack image sequences into a blend file unfortunately).
