### ISSUE TITLE
Meshswap Issues

### ISSUE THREAD

**Issue by KittenCat1080ti** [TheDuckCow/MCprep#176]
This Issue is in two parts, 1: Optimizing meshwap meshes, 2: Torch issue

For the first one, It is less an issue, more a way to drastically improve performance, There is a lot of unused geometry that grinds blender to a halt when meshswaping a large amount of grass for example. (not the unnecessary geometry) This would likely need a person to go over all the models and clean them up by dissolving some edges.
![image](https://user-images.githubusercontent.com/71938947/99008611-81ab6880-2514-11eb-807e-7cf0859ac1e0.png)

Part 2: as is noted in https://github.com/TheDuckCow/MCprep/issues/175, some torches suddenly lose illumination once the timeline moves, this is because there are multiple torches apparently in the meshswap file, for some meshswaped torches, they are spawned as torch 1, some as torch 2, and some as just torch, from what I can see, this is because the torch is to be made of multiple torches, all swapped in the same spot(I made this assumption based on the fact that one has very low light and flickers, others have constant full light).

**Comment by TheDuckCow** [comment]
Apologies for the delayed reply, thanks for laying out the two issues. On this issue thread I'll focus on 1 since 2 is reported on the other, which I've now labeled as a bug.

Regarding the unused geometry, I can see the argument for this. Dissolving faces though would have adverse affects on the animation of wind swaying grass. Meshswap is always recommended to be used only on a small part of the world near the camera as indeed, otherwise it will end up as a lot of extra geo. I also don't want to commit to optimizing the meshes in a very specific way unless knowing it will be applied and useful for everyone universally. There are some meshes, like the bricks, which I would agree to the argument to optimize since they are static.

**Comment by TheDuckCow** [comment]
Closing this issue being quite old now, but let me know if the above didn't help or you would still argue for different behavior. Happy to take the point of view in.

The issue on torches Im tackling different, I thought it was already resolved in the most recent update, but some people are still reporting similar or related issues that I will be investigating.
