### ISSUE TITLE
McPrep Not Using Extra Maps

### ISSUE THREAD

**Issue by CompilethisBuildthat** [TheDuckCow/MCprep#183]
When using packs like VanillaAccurate 512x  OldPBR, only the diffuse (or base colour) map is used, with the normal and specular maps blank on both SEUS and Specular [Link To Pack](https://vanillaccurate.space/2021/01/23/vanillaccurate/)

**Comment by StandingPadAnimations** [comment]
Old PBR only uses specular and diffuse maps. Normal maps are found in LabPBR.

**Comment by CompilethisBuildthat** [comment]
Any idea on when LabPBR support is coming? I heard it was being worked on.

**Comment by StandingPadAnimations** [comment]
It was already introduced a while back. The SEUS option is LabPBR. Just swap the texture pack like normal, select prep materials on the side, and change it to SEUS

**Comment by CompilethisBuildthat** [comment]
Ah, I'm probably thinking of POM, which I don't think is supported but would be cool.

**Comment by CompilethisBuildthat** [comment]
Ok, tried using the LabPBR version of VanillaAccurate, leaves, water and grass (not blocks) look very wrong on both EEVEE and Cycles
![image](https://user-images.githubusercontent.com/75911458/106805118-2b0a8200-665e-11eb-86eb-6b6de0eaf42f.png)

**Comment by TheDuckCow** [comment]
Is the issue that the materials look "emissive" (lighting up?). I noticed some packs seem to have it reversed, so would likely need to be another configuration/style dropdown in MCprep.

Did you also try loading using the "Specular" workflow (which is the default when prepping with 'extra passes'). What did that output look like?

**Comment by bytzo** [comment]
LabPBR and SEUS are both different formats of [channel packing](http://wiki.polycount.com/wiki/ChannelPacking), which allow for loading multiple PBR maps such as metalness, roughness, and emission using one image file. Each of these maps are stored in different channels of the image, such as the red, green, blue, and alpha channels.

MCprep currently only supports loading PBR resource packs with the SEUS format of channel packing. The SEUS format stores glossiness in the red channel, metalness in the green channel, and emission in the blue channel of the image file with the `_s.png` extension. Also, the red, green, blue, and alpha maps are stored in the file without a special extension, the normal map is stored in the RGB channels of file with the `_n.png` extension, and the displacement is stored in the alpha of the normal map. (note displacement is not supported with MCprep at this time)

There is also support for the specular format (also known as OldPBR), which only contains a grayscale specular map in the image file with the `_s.png` extension. The format for the red, green, blue, alpha, normal, and displacement maps is the same as the SEUS format. This isn't exactly PBR, which is why I refer to it as the specular format.

The LabPBR format is not currently supported by MCprep. Like the SEUS and specular formats, it stores the red, green, blue, and alpha maps in the file without a special extension in addition to the normal and displacement maps in the file with the `_n.png` extension. However, the file with the `_s.png` extension is different. LabPBR will use the red channel for glossiness, the green channel for metalness, the blue channel for both porosity _and_ SSS, and the alpha channel for emission. ([source](https://github.com/rre36/lab-pbr/wiki/Specular-Texture-Details)).

This means if you try loading a LabPBR resource pack with MCprep using the SEUS format, the porosity and SSS maps will be used as emission. Because of this, textures with SSS such as leaves and grass with appear emissive, as we can see in the screenshot above. In order to solve this issue, proper support for LabPBR will need to be added.

I was working on this initially when adding support for the SEUS format, however I did not end up finishing it due to the complexity of the format (multiple maps are stored in one channel). I may finish this in the future, however there is no guarantee for this as I might not have enough time. If anyone is interested, it is possible to add LabPBR support by adding a `texgen_labpbr()` function in the `materials/generate.py` file. This function should generate the nodes part of the LabPBR format and connect them to given outputs (so that it may work with principled and non principled shaders). See the [`texgen_seus()`](https://github.com/TheDuckCow/MCprep/blob/17c81dace912986e79b52ae28d4e36c32459c0b5/MCprep_addon/materials/generate.py#L1102) function as an example.

Another alternative is to use an image processing tool to swap the blue and alpha channels with each other in the image file with the `_s.png` ending. This will essentially convert LabPBR into SEUS, while loosing SSS and porosity (since SEUS does not support it). This may however be a hassle if the resource pack is large. A better solution is to implement proper LabPBR support, described above.

**Comment by CompilethisBuildthat** [comment]
> Is the issue that the materials look "emissive" (lighting up?). I noticed some packs seem to have it reversed, so would likely need to be another configuration/style dropdown in MCprep.
> 
> Did you also try loading using the "Specular" workflow (which is the default when prepping with 'extra passes'). What did that output look like?

Did try, but no change, I'll try Bytzo's suggestion and will close the issue if it works

**Comment by CompilethisBuildthat** [comment]
Closing this issue as I don't really understand how blender addons are programmed, and I think I will wait and see if LabPBR is ever added, thanks for the help.
