### ISSUE TITLE
some eyes go completely white in rendered view

### ISSUE THREAD

**Issue by epicdemon344** [TheDuckCow/MCprep#188]
I placed a zombie in my blender world and it looked fine when looking in solid view but when I switched to textured or rendered view the zombies eyes went completely white and the same went for a villager I put in as well. I don't know what to do to fix the issue.
![image](https://user-images.githubusercontent.com/79049133/107879186-43d12e00-6ecf-11eb-9e79-8addbe3b3888.png)
![image](https://user-images.githubusercontent.com/79049133/107879192-5186b380-6ecf-11eb-9d56-ce8b42cc4604.png)

**Comment by TheDuckCow** [comment]
I believe this is specifically due to the materials on that rig. If when you spawn the zombie, you can turn off "prep materials" in the popup (appears in the bottom left of the 3D view right after spawning), that will ensure original materials are use.

![turn off reset](https://user-images.githubusercontent.com/2958461/109440131-191ec380-79ff-11eb-82b9-59b438044d82.png)

I'm marking this as an enhancement though as I think we could do better about assigning a default respects prep materials better. But it's good in general to be intentional when using the prep materials toggle, it's on largely for compatibility reasons (ie to make materials created in cycle work in Eevee better or for Blender Internal - and yes, there are still blender 2.7x users of MCprep!). Let me know if you notice this on any other rigs too, I can mark it as a combined issue.

**Comment by TheDuckCow** [comment]
Side note if you've already been animating with the rigs in the scene and you want to not lose your work by respawning another rig, just select the eye mesh on the rig, and go into the materials tab and customize the material to be the color you want.

**Comment by TheDuckCow** [comment]
Closing this issue as I've resolved it locally by making a material change in the source rig, so eyes will not go white even when using prep materials on Zombies.
