### ISSUE TITLE
Error when installing on Blender 2.93 alpha

### ISSUE THREAD

**Issue by Endertainer** [TheDuckCow/MCprep#191]
# Updates by TheDuckCow

**MCprep support for Blender 2.93 is in progress.**

By nature, early builds of new blender versions can break addons and other features of blender in general. While the goal will be to ensure MCprep is always up to date, it will naturally lag a little behind beta and especially alpha versions of blender where things are still changing (and code fixes today may mean redoing the same fixes again tomorrow if the affected area is further revised by the Blender Foundation).

Please do not post new "Doesn't work in blender 2.93!!" issues, but rather feel free to add other comments here if you have something to add.

# Original post

So I tried to install the latest MCprep into blender 2.93 alpha and I got this message.
![blender_3Mo1ByG1az](https://user-images.githubusercontent.com/57242521/109436507-2a99b700-7a63-11eb-8e3f-8a88ec1c7558.png)

**Comment by TheDuckCow** [comment]
Thanks for sharing this, I will take a look. Double check on your side that restarting blender first doesn't fix the issue though!

**Comment by Endertainer** [comment]
I tried restarting blender but I still got the same problem. I even tried using the latest version that I can get but it still the same. Though in 2.92 it works fine. I also tried to install some of the other versions into blender 2.93 but still getting the same error.

**Comment by TheDuckCow** [comment]
Confirmed. And it doesn't look like a simple fix upon initial investigation. I'm going to take over this thread to make it the official "2.93 progress" issue tracker. Thanks again for taking the initial steps here!

**Comment by Endertainer** [comment]
Your welcome

**Comment by TheDuckCow** [comment]
Tracking additional notes. As mentioned above, MCprep seems very fundamentally broken in the current build of Blender 2.93. I will need to do more research to understand what is changing. Writing some notes and related links to help out my future self:

- [Doc on 2.93 Python API changes](https://wiki.blender.org/wiki/Reference/Release_Notes/2.93/Python_API), noting the upgrade to Python 3.9
- The addon is complaining about issues associated with registering or accessing property values apparently. This could have something to do with the current compatibility workaround MCprep has in place to support property registration pre-annotation python support (ie in Blender 2.7x).
- It seems that some things under the hood are still registering if I e.g. disable the update/items callbacks for property definitions, this lets MCprep at least enter an enabled state, but nothing draws successfully.
  -  In this mode, operators are defined, but not functioning. Even built in blender operator calls seem to fail. E.g. this after trying to press teh "open help" button which otherwise seemed to almost be working:
 
```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/Users/patrickcrawford/Library/Application Support/Blender/2.93/scripts/addons/MCprep_addon/tracking.py", line 806, in wrapper
    res = function(self, context)
  File "/Users/patrickcrawford/Library/Application Support/Blender/2.93/scripts/addons/MCprep_addon/util_operators.py", line 167, in execute
    bpy.ops.wm.url_open(url=self.url)
  File "/Applications/Blender 2.93/blender.app/Contents/Resources/2.93/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties:  WM_OT_url_open.url expected a string type, not _PropertyDeferred
```
  - Note how WM_OT_url_open is not even an MCprep defined operator; it works when calling directly like `bpy.ops.wm.url_open(url="http://theduckcow.com")`
  - But it raises an error (in the copy block again) when trying to set the property in a draw panel.
  - All in all, issues largely seem associated to registering and accessing properties. Also likely will be worth waiting for future build updates, things clearly might change and more information about these issues will surface.

**Comment by TheDuckCow** [comment]
Closing this issue as the release is now out.
