### ISSUE TITLE
materials overlay being weird

### ISSUE THREAD

**Issue by Jelcoo** [TheDuckCow/MCprep#198]
When I use a overlay on a grid, the texturing is weird (Look at the floor). What can cause this, and how to fix this?
![Loeki en ik](https://user-images.githubusercontent.com/53396500/114754192-9789b780-9d58-11eb-90e1-6b77de6e9569.png)

**Comment by Jelcoo** [comment]
(This is with all materials)

**Comment by TheDuckCow** [comment]
This is quite interesting. Is this something new (e.g. with the recent update), or are you unsure (e.g. if this is the first time you are trying this out)? Also, were the materials applied using the material library?

I'd also double check you have properly UV unwrapped the meshes, go into edit mode and press u to unwrap uv.

**Comment by Jelcoo** [comment]
> This is quite interesting. Is this something new (e.g. with the recent update), or are you unsure (e.g. if this is the first time you are trying this out)? Also, were the materials applied using the material library?
> 
> I'd also double check you have properly UV unwrapped the meshes, go into edit mode and press u to unwrap uv.

It is my first time using it, and I use the material library. When I do unwray uv, it looks like this
![blender_ZWoLkjaYPz](https://user-images.githubusercontent.com/53396500/114908117-1267d680-9e1c-11eb-801d-5c35480854c9.png)

**Comment by Jelcoo** [comment]
(I removed the skins, so that isnt a bugg)

**Comment by TheDuckCow** [comment]
I think this makes sense then. The standard default UV unwrap will indeed by not scaled to the way you want, so you'll want to go into the UV editor and scale it out further to be the size you want. Generally if I'm adding textures manually in this way, I try to make sure I use a specific size of mesh (e.g. set the plane to be 10x10) and then in parallel use the "reset" option for UV (to scale it to be bounds size), and then similarly scale it by 10x, so that it matches the typical 1m = 1 block = 1 texture repeat.

**Comment by Jelcoo** [comment]
Thanks!
![blender_gNGc268rMT](https://user-images.githubusercontent.com/53396500/114989451-b773c500-9e97-11eb-958f-0a71e981569e.png)

**Comment by TheDuckCow** [comment]
Sure thing!
