### ISSUE TITLE
I have a blender issue

### ISSUE THREAD

**Issue by Danieli12** [TheDuckCow/MCprep#21]
When i press 0 on the camera my Minecraft world disappears.

**Comment by TheDuckCow** [comment]
That sounds more like an issue for using blender than MCprep, so in the future consider looking elsewhere for support to get quicker responses. 

By pressing zero, you have either changed which layer is active (in the 3D view, at the bottom where it has those boxes) or you have simply gone into the camera view and the camera is in a position where you can't see the world, you may need to try and rotate it. 

Closing due to being a non-MCprep issue. Thanks for using the addon!
