### ISSUE TITLE
Blender Mcprep Issue

### ISSUE THREAD

**Issue by ghost** [TheDuckCow/MCprep#221]
(Big world)
https://cdn.discordapp.com/attachments/808374658180841562/856307458335440976/unknown.png

**Comment by TheDuckCow** [comment]
Unfortunately, this appears to be an issue in blenders own OBJ importer. Happens to be one of the bug reports I get through that automated reporter the most, but since it's not MCprep code, there's not much I can do.

But, I would love it if you could confirm my understanding. For this world which was giving you an error when importing through the MCprep Import World button, can you try doing the same manually through File > Import OBJ?

And if possible, please try once with the below setting on, and with the setting off. As this may also be part of this issue, since it seems to be related to its own split mesh code.

<img width="822" alt="split obj" src="https://user-images.githubusercontent.com/2958461/123546475-add5cb80-d72a-11eb-86bb-640297a45b54.png">

(this is in the popup where you when select your obj file to import, but before you press Import OBJ)
