### ISSUE TITLE
Error Texture

### ISSUE THREAD

**Issue by Ahmadqura** [TheDuckCow/MCprep#232]
Why is my texture like this?

![image](https://user-images.githubusercontent.com/88262868/127759853-8e63878f-1ff5-41cb-9588-432fa7d15fe4.png)

**Comment by TheDuckCow** [comment]
Yes, that is very interesting indeed. Seems to me like an exporter issue. Were you using jmc2obj or Mineways? Can you also share a screenshot of what it looked like *before* pressing any prep materials function in MCprep? Maybe even using the File > Import > Import Obj option to load the world, instead of MCprep's method?

**Comment by Ahmadqura** [comment]
First step - Click "N" and click MCprep. After that I click "jmc2obj" and click "OBJ world import". The last step - I click "Material Preparation" done

Note: The world is rendered with "Mineways"

**Comment by Coppertine** [comment]
That might be the issue, you exported the obj using Mineways and attempted to import through MCPrep using the jmc2obj. You should instead click on Mineways, then OBJ World import

**Comment by Ahmadqura** [comment]
before I put my world in, I tried it on the initial block when the blender started and the result is still the same.
for example like in the picture, I use "acacia_planks" but the texture is weird

![image](https://user-images.githubusercontent.com/88262868/127778942-6702e5b6-e190-493c-b4de-526f059b6fb2.png)

**Comment by TheDuckCow** [comment]
In this case, it's because the UV map of the default cube is not made for applying Minecraft textures. If you were to go into the UV editor and reset the layout (so that each face took up the whole scene), you should find that it works.

However this is different than the materials that get assigned when loading via Mineways. And in fact, the Mineways import doesn't look like it's scaled or anything, it just looks like the wrong textures are assigned to given blocks. I might suggest trying to completely remove your Mineways install/folder (including any adjacent files such as texture outputs), and re-download the latest and see if that resolves the issue.

**Comment by TheDuckCow** [comment]
Closing this issue, feel free to reply if you still need help on this.
