### ISSUE TITLE
Texture's transparent issues while using "Item from file"

### ISSUE THREAD

**Issue by SolomonGarrett258** [TheDuckCow/MCprep#240]
![glitch](https://user-images.githubusercontent.com/86562845/130569940-e297e555-1800-4007-8c78-01e2569f7c43.png)
![glitch1](https://user-images.githubusercontent.com/86562845/130569947-cd335555-aeec-4c81-a22f-763bb1e785ad.png)

While I'm importing some third-party textures as items. Some of the textures can't display correctly.
Both of those guns are using the same settings (p.s. the high value of "Max pixels is for HQ texture)

![jimmy_b682_l](https://user-images.githubusercontent.com/86562845/130571011-faf7536f-9da5-4f05-902f-9553a55af065.png)
![blue_tundra_l](https://user-images.githubusercontent.com/86562845/130571014-ce573f5c-bc77-4b8c-a47e-e9fc1b75cff7.png)

Here're the files

**Comment by TheDuckCow** [comment]
While not designed for high res, it should technically still work. Odd that one appears fine and the other not. All that being said though, at this resolution, I wonder if you should just have an image plane, since the pixels with aliasing won't translate well to edges in a pixelated mesh like ones this spawner creates.

**Comment by TheDuckCow** [comment]
Closing this issue as I believe UV shifting has been addressed in the v3.2.6 update to be released later today.
