### ISSUE TITLE
Transparency not working with jmc2obj v113

### ISSUE THREAD

**Issue by Tiefseetauchner** [TheDuckCow/MCprep#246]
Hi! I couldn't find an issue directly reporting this, so here I go,
When prepping the materials, MCPREP doesn't connect the Alpha point to the Principled BSDF Node
I switched from Windows to Linux recently, and started having the problem with Linux, but I can hardly imagine that being the reason?
I'm sorry if I overlooked something and it's obvious
No, I don't have "Make all Materials solid" enabled, it happens with the default settings

Here a neofetch if that helps at all 
```     -/oooooooooooooooooooo+ooo/-         OS: Ubuntu Cinnamon 21.04 x86_64 
    .+oooooooooooooooooo+/-`.ooooo+.       Kernel: 5.11.0-34-generic 
   :oooooooooooo+//:://++:. .ooooooo:      Uptime: 4 hours, 5 mins 
  /oooooooooo+o:`.----.``./+/oooooooo/     Packages: 2912 (dpkg), 17 (snap) 
 /ooooooooo+. +ooooooooo+:``/ooooooooo/    Shell: bash 5.1.4 
.ooooooooo: .+ooooooooooooo- -ooooooooo.   Resolution: 1920x1200, 1920x1080, 2048x1152, 2048x1152 
/oooooo/o+ .ooooooo:`+oo+ooo- :oooooooo/   DE: Cinnamon 4.8.6 
ooo+:. .o: :ooooo:` .+/. ./o+:/ooooooooo   WM: Mutter (Muffin) 
oooo/-`.o: :ooo/` `/+.     ./.:ooooooooo   WM Theme: Windows-10 (Windows-10) 
/oooooo+o+``++. `:+-          /oooooooo/   Theme: Windows-10 [GTK2/3] 
.ooooooooo/``  -+:`          :ooooooooo.   Icons: Yaru [GTK2/3] 
 /ooooooooo+--+/`          .+ooooooooo/    Terminal: gnome-terminal 
  /ooooooooooo+.`      `.:++:oooooooo/     CPU: AMD Ryzen Threadripper 2950X (32) @ 3.500GHz 
   :oooooooooooooo++++oo+-` .ooooooo:      GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
    .+ooooooooooooooooooo+:..ooooo+.       Memory: 13328MiB / 31960MiB 
      -/oooooooooooooooooooooooo/-
        `-/oooooooooooooooooo/:`                                   
            .-:/++oooo++/:-.```

**Comment by StandingPadAnimations** [comment]
MCprep doesn't connect alpha to a principled bsdf, it instead uses an older trick for easier compatibility between older versions of Blender. Also, can you send a screenshot of the nodes(neofetch doesn't help that much with addon issues)

**Comment by Tiefseetauchner** [comment]
Hey!
![image](https://user-images.githubusercontent.com/48085877/136671213-abb8dfcd-9e2f-4758-85f8-7514b07bca6f.png)
Here you go, I thought as much about NeoFetch, just got used to plonking it at the end of every github issue I report, sorry

**Comment by StandingPadAnimations** [comment]
Huh, this is weird. The alpha output of the texture should be in one of the mix shader nodes. I remember coming across this issue due to some exporting issues. Are you using the newest version of jmc2obj?

**Comment by StandingPadAnimations** [comment]
cause if so, use the previous version(if your world doesn't use 1.17 blocks)

**Comment by StandingPadAnimations** [comment]
That's an issue. Maybe try re-exporting the world and if it still persists, post it as an issue on the jmc2obj github

**Comment by Tiefseetauchner** [comment]
![image](https://user-images.githubusercontent.com/48085877/136671454-f92f4cff-043a-457f-b095-72360094b905.png)
It looks like this when importing, And I'm using the most recent jmc2obj version

**Comment by StandingPadAnimations** [comment]
MCprep uses the mtl file jmc2obj generates alongside the obj in order to do materials. If jmc2obj makes a messed up one, MCprep messes up

**Comment by TheDuckCow** [comment]
To more explicitly call out what is happening, the raw OBJ is being imported where it loads the same texture block twice, one where it assigns the image with a non-color data block, and the other with color. As of right now, since alpha is the only use of these textures, it shouldn't matter, so the MCprep update I'll be making is to just infer when the block should be used for transparency purposes anyways if the source is using an alpha channel. 

<img width="1126" alt="non-color-block" src="https://user-images.githubusercontent.com/2958461/144689776-19043163-92de-4304-a589-57d73e2ffe11.png">

**Comment by TheDuckCow** [comment]
For the manual workaround, one should make two changes:

1) Material nodes: Connect the output of the Alpha (unused post Prep materials) into the alpha channel of the Principled shader.
2) Properties > Materials tab: Change to hashed alpha for both blend mode and shadow mode (if using Eevee).

See screenshot below:
<img width="566" alt="adjustment" src="https://user-images.githubusercontent.com/2958461/144690079-69a560ab-3a38-4cd6-90b6-ce2c244f6947.png">

**Comment by TheDuckCow** [comment]
So it turns out that the root reason this stopped working as expected, is because of a [wildcard expansion](https://github.com/TheDuckCow/MCprep/blob/master/mcprep_data_base.json#L75) of `*_block` to infer blocks to be rendered as totally solid. With the more recent jmc2obj update, all materials have "_block" in their name (e.g. `minecraft_block-spruce_leaves`), and so all materials were being interpreted as solid. I've removed the wildcard expansion which resolves this issue, at the very minor cost of more materials will be rendered with transparency settings which will increase some render time, but better for things to work visually more consistently.

Track the milestone to see when this gets released: https://github.com/TheDuckCow/MCprep/milestone/5

Another step may broadly be to rename to remove the `minecraft_block` prefix from jmc2obj exports, but that can be considered separately.

**Comment by TheDuckCow** [comment]
Side note - for anyone who wants a faster more immediate short term fix before the release rolls out, you can follow these steps:

1) Go to the blender addons folder (you can find this path from the MCprep user preferences, e.g. where the meshswap filepath points to)
2) in the `addons/MCprep_addon/MCprep_resources/` folder, open the `mcprep_data.json` file
3) REMOVE the line that says `"*_block",`
4) Restart blender, good to go!
