### ISSUE TITLE
Update the list prep materials' emission blocks (including torches)

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#271]
A few blocks right now don't emit light by default. Torches are among them. Originally this was decided because it seemed unnatural that the entire torch would emit light (as it's an all or nothing material setting), but for people wanting something basic it's perhaps still better to have overall emission like that, and let them use meshswap when they want the more realistic closeups (meshswap torch and redstone torch models have only the according parts emitting lights).

**Comment by Timtaran** [comment]
:(

**Comment by Timtaran** [comment]
did latern emission or I have an a bug?

**Comment by TheDuckCow** [comment]
@Timtaran correct, lanterns currently are not automatically emissive. For the same rational that it would make all parts light emitting, including the non-light parts like metal, but I've decided now that it indeed makes sense it be included in the emissive list. (this goes for soul lanterns as well).

**Comment by TheDuckCow** [comment]
Would love to get feedback on the current state of these lines of code: https://github.com/TheDuckCow/MCprep/blob/dev/mcprep_data_base.json#L13-L34

I followed [this reference]9https://minecraft.fandom.com/wiki/Light) on light levels, with the assumption that anything that is only on when touched (e.g. redstone) should be left as non emitting, I also did not make low emission blocks like brown mushrooms, brewing stands, and blue ice emitting as I feel it would be strange unless it were made much subtler.

**Comment by rjp** [comment]
I applied that change and it mostly helps my scenes (although end rods aren't emitting on my M1 Mac but that might be a 3.1.0alpha issue since they work on my PC with 3.0.0.)

I think glow lichen and portals might be a bit too bright though - the portal is lighting up the mountain on the right (~30 blocks away) and the glow lichen is like a spotlight rather than a subtle glow.

![glow-lichen-portal](https://user-images.githubusercontent.com/10793/149315800-50ce9834-3c0e-4b07-8c77-a5cfba956b34.jpeg)

**Comment by TheDuckCow** [comment]
Thanks for the commentary. I'm going to close this in the meantime as resolved, but I created the above issue to track this point.
