### ISSUE TITLE
Installing Rig with multiple Collections

### ISSUE THREAD

**Issue by Endertainer** [TheDuckCow/MCprep#280]
Halo.

So I have a rig that I want to install to MCprep. But the issue is that based on your tutorial video (https://www.youtube.com/watch?v=z0Pif2suVZ4), the rig needs to be in one collection. And unfortunately, my rig comes in multiple collections. And I can't just remove all of them because some of them are important and the rig might not be working correctly without them.

![image](https://user-images.githubusercontent.com/57242521/150568467-6ef8b7bf-e915-4c06-8811-ac30d821f20a.png)

So, I propose a solution. What if, instead of requiring all rigs to be in one collection, why don't MCprep append collection with a specific name. Let's say that the collection that will be appended required an MCprep_ prefix.

![image](https://user-images.githubusercontent.com/57242521/150569004-a61b618b-ef1d-43db-b3f2-53c75b3368ef.png)

So in this case, MCprep will append the collection MCprep_SS_EndEdit_R4 with any collections inside.

**Comment by TheDuckCow** [comment]
Thanks for sharing this idea! Yes, I think this could be fairly reasonable. What do you think about more specific functionality: 

1. Search for the name "MCprep" in collections in a given file (case invariant)
2. If MCprep is not found anywhere in any collections in the file, just show all collections (ie current behavior)
3. But if MCprep is found, then *only* show those specific collections. In the UI, replace the text "MCprep" and any single leading or trailing space/underscore.

I am considering also doing a negative check too, something like if "MCskip" or "MCprepSkip" is found or something like this. Similar to the above, but would only function to exclude a collection if otherwise no collections had MCprep in the name at all (ie the case where it would just show all collections).

I think it would be a hidden power feature, but simple enough to implement and cover your needs. That seem right?

**Comment by Endertainer** [comment]
I think it's good. But I want that any collection inside the "MCprep" collection to be appended.

So let's say that I have a collection I named MCprep_Rig. And inside that collection, there's another collection named Mesh and the rigs armature.

And once I installed the Rig into MCprep, when I append the Rig, it will append the MCprep_Rig collection (the collection will be renamed to just Rig). And when I opened the "MCprep_Rig" collection, there will be the Mesh collection and the armature.

So MCprep will append collection with the MCprep_ prefix and any collection inside. So in my example above, it will append the MCprep_Rig collection with the Mesh collection inside of it.

**Comment by Endertainer** [comment]
Here's another example with my rig, SS EndEdit R4. Which is the reason why I want this feature to be added.

![image](https://user-images.githubusercontent.com/57242521/150633662-75af7da4-3a30-44b9-be68-9e50f413b3fd.png)

In this example, MCprep will append the MCprep_SS EndEdit R4 collection with all of the collections inside. While leaving Collection 2 and 3 untouched.

So when I append the rig, it will append the MCprep_SS EndEdit R4 collection (later renamed to SS EndEdit R4) with all of the collections inside. Like the Main Mesh, Ultimate, Animate, DISABLE ME, etc.

Also, if there's aren't any collection with the MCprep_ prefix, it will just revert to the old behavior.

**Comment by TheDuckCow** [comment]
Understood, thanks for clarifying and posting the follow up screenshot!

The good news is your main points around importing all sub collections already functions this way. I just tested this with a forked version of the axotle rig by setting the rigs folder to point to my test dir. I added some nesting of the collections with custom colors, and then spawned with MCprep, get this the below:

<img width="752" alt="sub colls" src="https://user-images.githubusercontent.com/2958461/150903643-7eac95c3-9c9e-414d-bde2-500030f3f425.png">

Since this seems to work as you are looking for, the primary thing to implement here is the filtering we suggested. Very doable! This will be in the next release (no explicit ETA, but hopeful for a couple weeks from now).

**Comment by Endertainer** [comment]
Nice 👍
I can't wait to try it out.

**Comment by TheDuckCow** [comment]
I am going to close this issue as the code has been committed, but please be aware **a release has not been created yet**. Still likely a week out. Once v3.3.1 out you'll be able to use this code. A nice improvement, as I generalized it to make it function similarly across all parts of MCprep including Mobs, Entities, and Meshswap.

The final behavior is to isolate if `MCprep` or `mcprep` is found in any collection names, then only include those. And on top of that, any collection names containing `mcskip` or `noimport` will be skipped (regardless of `mcprep` being in another collection name or not). This also nicely filters out some of those collections like "torch_flame_noimport" in current versions of MCprep's meshswap.
