### ISSUE TITLE
Block spawner doesn't prep materials, grayscale grass and more

### ISSUE THREAD

**Issue by 1HIRENSIDDARTH** [TheDuckCow/MCprep#288]
many blocks like grass block, grass and many more are getting half glitched rendered, i don't know why but i am getting them without color i am getting them rendered black and white ,please help me out
![image](https://user-images.githubusercontent.com/92012726/159953144-852e33f5-0aff-43c8-b3a3-ca59d2e16a43.png)

**Comment by TheDuckCow** [comment]
This is because blender is displaying the objects with the raw source image in solid mode, not accounting for the material shading. If you go into material mode or rendered mode, you should get the properly color shaded blocks. If that isn't working for some reason, please let me know.

**Comment by 1HIRENSIDDARTH** [comment]
no it is still the same i tried both modes

**Comment by 1HIRENSIDDARTH** [comment]
textures are same and reloading them is also not working

**Comment by 1HIRENSIDDARTH** [comment]
hello? my textures are still not getting corrected
please guide me out

**Comment by TheDuckCow** [comment]
I just replicated the issue myself, and realize it's largely because prep materials is not run on the block after the fact.

But, if I select the block and press prep materials, then it works as expected. Please try this, and again be sure to go into material mode.

**Comment by 1HIRENSIDDARTH** [comment]
thanks it works

**Comment by mguggenheim** [comment]
@TheDuckCow Thanks for the amazing tool! Wondering if there's a way to automate biome colors using MC Prep. For instance if I place a grass block and then press prep materials, wondering if I can prep them for a swamp biome so the colors are appropriate for that biome.

**Comment by TheDuckCow** [comment]
Hi @mguggenheim would love to have your thoughts and reactions in this issue thread:
https://github.com/TheDuckCow/MCprep/issues/269

It may not be able to work and function exactly as you are hoping, ie a direct translation from Minecraft, but maybe we can make some tools to make it a little easier. So happy to hear your end goal needs in that issue thread.

**Comment by StandingPadAnimations** [comment]
> @TheDuckCow Thanks for the amazing tool! Wondering if there's a way to automate biome colors using MC Prep. For instance if I place a grass block and then press prep materials, wondering if I can prep them for a swamp biome so the colors are appropriate for that biome.

Since no one is saying it, I think I'll say what should have to be said

There is a separation between the responsibilities of MCprep and the responsibilities of individual world exporters, based on the information they have. Biomes are sometime only world exporters have knowledge about since those are non-existent in the OBJ file format, so it's up to them to give MCprep (and stuff like it) the necessary info needed for MCprep to implement biome colors. 

MCprep only has the information that Blender gives it, which only has the information the world exporters give it. The lack of support for the feature in world exporters is the reason why MCprep doesn't support it. 

| World Exporters | MCprep| 
|-------------------------|-------------|
| Have the info Minecraft gives like biomes | Only have the info that Blender has been given, which is given by the world exporters|
| Should provide info on the world itself, since OBJs are really portable 3D models | Is only as good as what info world exporters give it |
| Provides textures | Uses textures to make materials | 

MCprep could use complex and slow algorithms to figure out the biomes, but it shouldn't have to if world exporters just gave the information in the first place. What tends to happen is that we forget that world exporters also need bug reports and feature suggestions, which is why issues like this occur. The following chain exists:

Minecraft ---> World Exporters read world files ---> export OBJ ---> Blender imports OBJ ---> MCprep does changes based on the info it has

One weak link in the chain, the rest of the chain is affected.

This isn't to bash on world exporter devs, they have a lot on their plate, but frankly I think what needs to be established are the responsibilities world exporters have and the responsibilities MCprep has. Simply establishing those boundaries would benefit both MCprep and world exporters.

**Comment by StandingPadAnimations** [comment]
I know what I've said will be extremely controversial, but it's the unfortunate truth. MCprep is only a single cog in the machine that is Minecraft rendering. You could have an extremely well made cog, but if all the other cogs are lagging behind, then do you expect the machine as a whole to run well?
