### ISSUE TITLE
texture collision

### ISSUE THREAD

**Issue by Czutrix** [TheDuckCow/MCprep#291]
Hi, I have a problem with textures one time when I was looking at grass I saw a little line above her.  Please, I need help!
[Zrzut ekranu 2022-04-23 o 21 34 06](https://user-images.githubusercontent.com/98060830/164943846-f6b2c830-b2b0-423e-aa79-ed7ccc953b61.png)

**Comment by StandingPadAnimations** [comment]
That's an extremely minor line. I think it's simply the camera's distance from the grass causing that. Therefore this isn't a bug with MCprep or Blender. If you're referring to the 2 intersecting lines above the grass, that's most likely the Blender UI.

I'll close this for now since I don't see any issues
