### ISSUE TITLE
using mcprep and wallpaper engine together

### ISSUE THREAD

**Issue by 5alidshammout** [TheDuckCow/MCprep#292]
here is my detailed question:
https://blender.stackexchange.com/questions/262462/blender-3d-scene-into-wallpaper-engine-with-effect-on-mouse-move
can anyone help, please?

**Comment by TheDuckCow** [comment]
I would suggest trying this:

After you have exported your fbx/obj files, try re importing them into a fresh blend file. If you can see textures and animations there, then it's a sign there's some issue with wallpaper on how it's importing fbx and obj files. I'm not familiar with the program to give further guidance, but this is a good first step to see where the issue is occurring. On the blender side, there are a number of fbx settings around animation so it's easy to not have the right settings on, hence testing by importing back into blender being a good test.

**Comment by 5alidshammout** [comment]
I did the test and it's all grey, even `prep materials` isn't done, what to do

**Comment by TheDuckCow** [comment]
That means the export isn't including materials (presuming you for sure were in material mode when you did the importing). Not sure if I have the exact answer for you here unfortunately, other than to play with the export settings making sure you select everything for OBJ when you run the export. Per random link [here](https://gamedevtraum.com/en/blender-tutorials-and-curiosities/how-to-export-a-3d-model-in-fbx-format-with-textures-in-blender/#:~:text=Go%20to%20File%20%3E%20Export%20%3E%20FBX,4.) you can also try changing the auto Path setting to Copy to ensure all data is copied. I'd also advise simplifying the materials as much as possible to not trip up the exporter.

**Comment by 5alidshammout** [comment]
I did like https://www.youtube.com/watch?v=kEP34CbPWUo and the link you sent, but both failed

**Comment by 5alidshammout** [comment]
before:
![image](https://user-images.githubusercontent.com/73162518/166634523-9ba08222-3a81-4263-98ac-63e2d2be2167.png)

after:
![image](https://user-images.githubusercontent.com/73162518/166634499-1d81a59a-363c-4fb1-a89e-e7f0e143fff1.png)

**Comment by 5alidshammout** [comment]
ok, I will try to go to discord, for a forum I went to https://blender.stackexchange.com/, but no one replied yet, but thanks so much for trying to help
