### ISSUE TITLE
Blender rig broken

### ISSUE THREAD

**Issue by Snipercupcakes** [TheDuckCow/MCprep#295]
https://drive.google.com/drive/folders/1L-IsUkJ2DXCwyjp0XpzFvHdYPBc6ydT3?usp=sharing The files are up there so basically rig is not working properly. I have a video included in the link above. I am using MCPREP. PC specs: M1 GPU & CPU MacBook air MacOS 12.3.1

**Comment by TheDuckCow** [comment]
Hi! Sorry for the delayed reply; @Snipercupcakes I don't have access to that google drive folder, can you try making it public? Are these specifically MCprep rigs, or from elsewhere? If from MCprep, can you specify which ones are not working and specifically in what way they are not working? Otherwise we may not be able to pick up on what the issue is easily.

**Comment by Snipercupcakes** [comment]
Actually, I fixed already, thx
