### ISSUE TITLE
Model index problem when export

### ISSUE THREAD

**Issue by schwarzsky** [TheDuckCow/MCprep#303]
Exporting model as `GLB` , just used "Prep Materials" feature.

But trying to view on any model viewer, looks like model blocks have an index problem.

![CYhI7uVz](https://user-images.githubusercontent.com/25959527/171973250-ef657c3f-84fd-4393-b9b3-66db5f8ce974.jpg)

**Comment by StandingPadAnimations** [comment]
What do you mean by index problem?

**Comment by schwarzsky** [comment]
I mean you can see blocks in front of other blocks as you can see in screenshot. Like trapdooors, redstone lambs etc. Screen shot explains itself.

**Comment by TheDuckCow** [comment]
Can you share what model viewer? Really it's going to be a limitation of that software - and your GLB export settings. If you are exporting to GLB, then I don't see much value in using prep materials anyways because it is designed to make materials work well *in blender* via shading nodes and blender render settings.Likely the culprit is that MCprep will treat materials as transparent, and some speed-oriented viewers will get tripped up with multiple levels of transparency.I doubt there's really anything to be done here other than try the "simple" material exporter, perhaps with "make solid" option ticked on. Consider also sharing a screenshot of a world export before MCprep is used, could help isolate where you might fix your issue. On Jun 4, 2022 1:28 PM, schwarzsky ***@***.***> wrote:
I mean you can see blocks in front of other blocks as you can see in screenshot. Like trapdooors, redstone lambs etc. Screen shot explains itself.

**Comment by TheDuckCow** [comment]
Just checking in to see if this is still an issue.

**Comment by schwarzsky** [comment]
Just updating about news. I was not minifying model when i try if it is a bug in MCPrep but seems like MCPrep works compatible with Blender -not for exporting and using in different renderer-.

If any of you guys has the index problem like me while using `gltf-pipeline` to minify model you can look to this issue: https://github.com/CesiumGS/gltf-pipeline/issues/614

Just decided MCPrep is not an shortcut for models while exporting, so i will try to find my way in scripting to automate most of the process (like making type closest or updating materials) if i can.

Thanks for your help and patiance!
