### ISSUE TITLE
Support for the new OBJ imported in Blender 3.2

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#305]
In Blender 3.2, a new C++based OBJ importer was added, massively improving performance for OBJ importing. Right now it is experimental, so until it replaces the existing OBJ imported, we'll have to manually enable it.

This should be relatively simple to add as #290 introduces the new getBV(major_version, minor_version) function in `utils.py`, so this should be simple to add

**Comment by TheDuckCow** [comment]
Just to clarify @StandingPadAnimations, to your understanding this issue can be closed right, since it's already automatically used? I also haven't researched this much yet, so it would help me too if you could point out where I can verify this (e.g. is it just a setting int he operator call, since the operator name is unchanged? Or is the new efficient way the only way inside Blender now)

**Comment by StandingPadAnimations** [comment]
> Just to clarify @StandingPadAnimations, to your understanding this issue can be closed right, since it's already automatically used? I also haven't researched this much yet, so it would help me too if you could point out where I can verify this (e.g. is it just a setting int he operator call, since the operator name is unchanged? Or is the new efficient way the only way inside Blender now)

As far as I can tell, the new importer is the only option, so I'll close this issue
