### ISSUE TITLE
Speed issues for Animate Textures

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#336]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I'm filling this out on behalf of someone else. They were using a custom texture pack which had animated textures. However, when they chose the animate textures option, the textures were too fast.

Example (while the magma block issue isn't showcased, the fire is definitely too fast in Blender compared to in game): [Video showcasing bug](https://cdn.discordapp.com/attachments/868999786148286479/1010689303891935342/Tex_Bug.mp4)

This seems to be an issue in multiple texture packs. While it is possible to slow it down, it might be best to either figure out the root cause, or add a slider to determine how slow the animation is.

### What steps are needed to produce the bug?

1) Prep materials with Texture swap
2) Animate textures

### What version of MCprep are you using?

3.4.1

### What version of Blender are you using?

Blender 3.2.1

**Comment by StandingPadAnimations** [comment]
They also have another video that showcases some more issues when trying to show the issue with vanilla textures: https://drive.google.com/file/d/1jOWpD58C-BpqCWuhscUF4CknGbavzyul/view

**Comment by TheDuckCow** [comment]
Yup. This is a known issue: https://github.com/TheDuckCow/MCprep/issues/161

The root issue is that animate textures works in a rather basic way right now. It's 1 tile in the texturepack = 1 blender frame, and is read in an image sequence. What this issue above outlines is the need to duplicate frames to match the active framerate. We would also benefit from doing some more image processing to allow even more advanced things like blending between frames and so forth. All doable within python, just requires some coordinated effort.

I'm going to close this in favor of the other task, since it's one and the same. Happily accepting assistance for anyone willing to contirbute
