### ISSUE TITLE
Texture pack swapping doesnt give geometry to a texture

### ISSUE THREAD

**Issue by blenderlover** [TheDuckCow/MCprep#349]
Hello! Im having an issue about texture pack swapping. I have a pack that has a bushy leaves texture in it. While swapping I dont see any bushiness in a tree model, (it only spawp the texture itself but doesnt add any deformation). do you have any idea how can i fix this?
![2022-10-20_20-35-53](https://user-images.githubusercontent.com/116278871/196951136-ca8b8f05-e34e-4ae3-af0a-d1eb0d022b7a.png)
![2022-10-20_20-33-31](https://user-images.githubusercontent.com/116278871/196951142-a605a115-9efc-4267-a87b-1a29c67b566b.png)

**Comment by blenderlover** [comment]
Thank you for your reply! I was hoping for something like that
![texture-bushy-leaves-1](https://user-images.githubusercontent.com/116278871/196983948-98bb1e52-4f94-4d41-8753-e13a14774cb4.jpg)

**Comment by Tiefseetauchner** [comment]
This is way out of scope for changing texture packs, as that would mean that function essentially has to meshswap

Meshswap is an option, but it might also be out of scope for meshswap, I wouldn't expect meshswap to change leaves (tho that might kick off configurable meshswap, which would be neat), but also that would make every leaf a seperate instance of an object and not just add the few bushy things. Jmc2obj has an option to load a texture pack, which also applies block models. It seems you are using mineways, which I have no experience with, but maybe there is an option as well. Using a texture pack like VanillaTweaks bushy leaves in the exporting step would probably be the best solution. Keep in mind, with leaves the biome color is applied in prep materials, and it misses out on other textures/materials that aren't the leave itself, so you'll end up with white bushy leaves:

![image](https://user-images.githubusercontent.com/48085877/197393113-0ad7e98a-3304-417a-a415-03833a0c9757.png)

You'll have to change the material manually, but that shouldn't be too dificult (using the existing but muted add color node)

Other than that, you can try adding your own mesh swap. I suspect this'll require (hard) coding it into the addon (you can probably then open a PR)

**Comment by TheDuckCow** [comment]
Indeed I see what you are saying, and as you mentioned yeah, texture swap operation is truly only _textures_. Shaders used by resource packs to modify and manipulate geometry work quite differently.

If there are custom block shapes defined by the resource pack, you could potentially import those using the block spawner, but it would be some manual effort either way.

You **could** try making meshswap work in its current form, by saving a mesh of the desired shape in the meshswap blend file that MCprep comes with (or better, point that to another file location, so it doesn't get overwritten when MCprep updates). As long as the object (block) name in the meshswap file matches the _material_ name of the matching block imported by jmc2obj for the leaves, it should do OK. Just make sure to run the process over a small area of your scene, as performance breaks down when modifying a large area/number of blocks.

The ultimate approach of changing the model geometry up front before exporting to OBJ is an excellent and more robust option too. I'm actually using jmc2obj myself, I stopped being able to use Mineways personally for awhile since I can no longer run the windows binary through an emulate on my OSX machine (sadly).

**Comment by TheDuckCow** [comment]
I'm going to close this issue since, as discussed, it's a feature design request that would need further evaluation and is not the simplest to do. Model spawning would be the way to go, if it could ever get some contributions to improve.
