### ISSUE TITLE
jmc2obj Prep Materials is broken

### ISSUE THREAD

**Issue by ThePoptartCrpr** [TheDuckCow/MCprep#35]
When I imported the .obj from the jmc2obj menu, everything's a solid color. When I click "Prep Materials", it freezes for a bit and then everything is purple. All of the textures are purple. 

I'm in Cycles Render and viewing in Material mode.

**Comment by ThePoptartCrpr** [comment]
This is what I mean:

![screenshot 223](https://cloud.githubusercontent.com/assets/25708063/26735121/626c8baa-4775-11e7-8969-5af050555b12.png)

**Comment by TheDuckCow** [comment]
Hello, sorry for missing this before. This happens when you have misplaced or relatively moved the path tot he textures. Prior to pressing mcprep, if you imported the model and have blender internal enabled you should see the textures, or they should be in the UV image editor from the image dropdown. If they are not there, it means the images got moved relative to the original .obj

**Comment by TheDuckCow** [comment]
Closing this issue since no response received, @ThePoptartCrpr let me know if you are still having troubles by commenting here.
