### ISSUE TITLE
Can't load in Mobs

### ISSUE THREAD

**Issue by Florixa** [TheDuckCow/MCprep#351]
### Did the issue happen after restarting Blender?

- [x] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Every time I try to load in a mob that isn't a player Blender Freezes and takes over 20min to load an entity such as a parrot.  
![image](https://user-images.githubusercontent.com/114229578/197972531-ff90e9cc-ac24-499e-bc46-7ee0825592b8.png)

### What steps are needed to produce the bug?

Once in Blender go to top section and press "Add" which is in between select and object. Then click on MCprep, then on Mob Spawners and then on a mob (Not a Player character).
(Steps circled with red in image)
![image](https://user-images.githubusercontent.com/114229578/197973249-141196b9-770d-4a1d-875f-df4c657cb2bc.png)

### What version of MCprep are you using?

3.4.1

### What version of Blender are you using?

3.3.1

**Comment by TheDuckCow** [comment]
Sorry for the delayed reply - can you try reinstalling MCprep after completely deleting it? Can you also try running blender as an admin user? Furthermore, make sure you are in solid mode first, in case trying to add something while in rendered mode slows it down (though I see you are already in solid mode, so not the issue here). As a final step, I'd suggest trying to remove any other custom addons you've enabled, in case they are conflicting somehow.

**Comment by TheDuckCow** [comment]
Closing this out due to inactivity, please comment back if still having an issue.
