### ISSUE TITLE
The snow weather effect resets and stops working when saving, closing and opening the same project in blender

### ISSUE THREAD

**Issue by GeometricosGitHub** [TheDuckCow/MCprep#353]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

So i was making a blender proyect, i import the assets from mcprep, i import the snowy weather effect for a video, and when you save the project, close blender and open blender, the effect doesn't work,

![waza](https://user-images.githubusercontent.com/102566094/198593413-2d954106-a195-4028-a1ed-bd06d0f41f85.png)

that image is when opening the project.

### What steps are needed to produce the bug?

So when you open blender, import assets from mcprep, import the snowy weather effect, and when you save the project, close blender and open blender, the effect doesn't work, it doesn't show the snowflakes that it should. im using blender 2.93 and when it happened. I just see the the cube when should be apperar the snowflakes.

![waza](https://user-images.githubusercontent.com/102566094/198593413-2d954106-a195-4028-a1ed-bd06d0f41f85.png)

### What version of MCprep are you using?

MCprep 3.4.1

### What version of Blender are you using?

Blender 2.93

**Comment by TheDuckCow** [comment]
Please see if this sounds like your issue here, in which case it is known and we are working on the automatic solution - in the meantime, you can manually mark the particle source as a fake user from the outliner. There is a video showing this workaround in the issue comment linked below

https://github.com/TheDuckCow/MCprep/issues/343#issuecomment-1304855339
