### ISSUE TITLE
"Open Mineways" not working.

### ISSUE THREAD

**Issue by 01beaker** [TheDuckCow/MCprep#36]
I have set up the mineways in the user settings (as shown in the image): ![prefview](https://user-images.githubusercontent.com/24231179/27068867-c3c490c2-4fd7-11e7-87e4-db7e1e5649a1.JPG) 
![selected](https://user-images.githubusercontent.com/24231179/27069041-98788418-4fd8-11e7-9242-03ba0fa60860.JPG)
 but I am getting an error as I try to launch Mineways from inside of blender (as shown in image): 
![errorinblender](https://user-images.githubusercontent.com/24231179/27069008-6e4061c0-4fd8-11e7-8ce0-04d2f42c256d.jpg)
 I do not know if this is an experimental feature, or if this is my own issue.

**Comment by TheDuckCow** [comment]
Thanks for sharing the screenshot and setup. I'll have to explore, but based on the error popup it seems that the Python version your blender has is missing some typically available modules. I'm not sure what I'll be able to do this, but will explore. The feature is slightly better tested on OSX than windows so that could be one reason. 

Question: how did you install blender? Just running the exe from a zip file, or did you run the actual blender installer?

**Comment by 01beaker** [comment]
I ran the actual blender installer, but I will try the repair option.

**Comment by TheDuckCow** [comment]
Instead of that, can you please try actually "not" installing - instead, just download the windows zip version instead of the installer. Then just extract the zip folder somewhere (all of it) and then run the blender exe file in place in that folder. See if the same happens. 

My guess is that the installer version doesn't have a full version of Python.

**Comment by TheDuckCow** [comment]
Just checking in - did you manage to try with a full install/out of the zip file?

**Comment by Kitthefox** [comment]
I did the same thing, plus I got blender from Steam, mcprep from your link, and mineways from the website, Still getting the same exact error.

**Comment by TheDuckCow** [comment]
Hello, thanks for bringing this to my attention. For some reason it's not using the correct path to open the executable. @Kitthefox, can you share a screenshot + copy the exact text of the contents of the mineways exe and finally also a screenshot of the mineways exe as it appears in your windows file browser?
