### ISSUE TITLE
Frog's Black Plane Issue

### ISSUE THREAD

**Issue by Abbimation** [TheDuckCow/MCprep#392]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I was creating a new character, and then I went to UV Editing and messes up the entire rig.

### What steps are needed to produce the bug?

Remove black planes from the frog rig.

Add keys to it's feet. 

Have the image of the temperature of the frogs separated.

### What version of MCprep are you using?

MCPrep 3.4.1

### What version of Blender are you using?

Blender 3.4

**Comment by TheDuckCow** [comment]
Hi @Abbimation I am indeed seeing the default frog is having some black in Eevee specifically, due to blend mode being set to Opaque. We'll fix this in an upcoming release, in the meantime just hit this update:

<img width="1022" alt="Screen Shot 2023-03-13 at 7 24 58 AM" src="https://user-images.githubusercontent.com/2958461/224730595-ddf394b0-7495-4be7-a24d-fd25e06b319b.png">
