### ISSUE TITLE
Import World Doesn't Work.

### ISSUE THREAD

**Issue by Abbimation** [TheDuckCow/MCprep#406]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I was trying to import the world the other way around and then I saw the error.
![00F8D5BB-360E-4B48-90D7-6F22C5DA3669](https://user-images.githubusercontent.com/127754075/227056207-a25e795f-e020-4b1a-a8d4-9671695898cd.jpeg)

### What steps are needed to produce the bug?

1. Fixed the issue in the next update.

### What version of MCprep are you using?

MCPrep 3.4

### What version of Blender are you using?

Blender 3.4

**Comment by StandingPadAnimations** [comment]
Already a known issue (as mentioned in #397), it's already been fixed and will be pushed in the next update.

General gist is that in MCprep 3.4.2, a conversion function was added for ACES compatibility (if you've never heard of ACES, don't worry about it, all you need to know is that it's a pain with OBJs). The function makes the assumption that the OBJ and MTL have the same name and that it's fine to swap out `.obj` for `.mtl`.

Now I assume you're using Mineways? If so, then the issue is that Mineways replaces spaces in the OBJ name with underscores when generating the MTL file. For example, `Beach Town.obj` will have an MTL called `Beach_Town.mtl`. The current workarounds are to either remove the underscores in the MTL filename or don't use spaces in filenames (the former is a quick fix, the latter is just a general good habit since spaces in filenames are an absolute nightmare for programmers)
