### ISSUE TITLE
Open Mineways broken on MacOS

### ISSUE THREAD

**Issue by Zachadactyl** [TheDuckCow/MCprep#410]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When I go to open Mineways through MCprep (v3.4.3) it says I need to install or watch tutorial.  I am using the latest version of Mineways for MacOS (macOS 13.2.1) and have set the path to Mineways.app in the MCprep preferences.  Blender version 3.4.1
![Screenshot 2023-03-26 at 6 13 52 PM](https://user-images.githubusercontent.com/89289754/227818471-11a9d3f6-bdbf-4f8f-b1a3-17e26a3dd566.png)
![Screenshot 2023-03-26 at 6 14 15 PM](https://user-images.githubusercontent.com/89289754/227818472-a6033221-2026-4089-9649-7802685e0b4b.png)

### What steps are needed to produce the bug?

Run macOS Ventura 13.2.1, install Mineways for MacOS (without Wine), Blender 3.4.1, and MCprep 3.4.3.  Set the location path to the .app file, and in the "N-menu" select open Mineways.

### What version of MCprep are you using?

MCprep 3.4.3

### What version of Blender are you using?

Blender 3.4.1

**Comment by StandingPadAnimations** [comment]
The MacOS version of Mineways is extremely outdated, and should not be used

**Comment by TheDuckCow** [comment]
Per the point above, the native Mineways for OSX is not going to work since it's so old and wouldn't be able to read your most recent worlds anyways (I imagine). Unfortunately with apple silicon, I've been unable to rune Mineways via Wine for some time. Closing this as there's not really a workaround at this stage, but we could always log a feature improvement if there is something someone can propose.
