### ISSUE TITLE
Geometry Is Missing On Properties.

### ISSUE THREAD

**Issue by Abbimation** [TheDuckCow/MCprep#421]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

The geometry part of the OBJ world importing is missing on properties.

### What steps are needed to produce the bug?

Add geometry on properties in the OBJ world import setting.

### What version of MCprep are you using?

MCPrep 3.4.3

### What version of Blender are you using?

Blender 3.5

**Comment by StandingPadAnimations** [comment]
> ### What steps are needed to produce the bug?
> Add geometry on properties in the OBJ world import setting.

That's not enough info to go by. Give a step by step process of what you did

**Comment by StandingPadAnimations** [comment]
@Abbimation I'll be closing this report on the basis that there isn't enough information nor has any extra information been given for more than a month. The issue was opened on May 9th, and it is currently June 18th.

You can still comment on this issue, but I can only reopen the issue if the steps to reproduce have been updated with enough information for us to recreate the issue on our side. As it stands, "Add geometry on properties in the OBJ world import setting." is not enough for us to recreate the bug.
