### ISSUE TITLE
Can't turn mcprep on

### ISSUE THREAD

**Issue by CrazyLevi** [TheDuckCow/MCprep#43]
When I go to user and try to turn mcprep on it creates this very long wrong message that says it's something wrong with the file. How can I fix this?

**Comment by TheDuckCow** [comment]
Hello, can you share a screenshot of the error you get? 

For more immediate troubleshooting, make sure you are installing it as a .zip (following [this video](https://www.youtube.com/watch?v=i6Ne07-eIyI) exactly), and that you are using e.g. blender 2.79 (it may not work correctly yet with Blender 2.8 or really old versions of blender e.g. below 2.72).

**Comment by TheDuckCow** [comment]
Hello,

Can you take a screenshot of the error and share here, and also let me know what operating system you use? I would also make sure you are using an official recent release of blender (eg 2.79, but not 2.8 since that isn’t fully released eg and changes many things). Additionally, make sure you are installing it as a .zip file 

Patrick

**Comment by CrazyLevi** [comment]
I use blender 2.79 and windows 10. I can send you a screenshot later today

**Comment by CrazyLevi** [comment]
https://imgur.com/a/8RtdZTR here is it

**Comment by TheDuckCow** [comment]
Thanks for the screenshot. It appears to be an issue with the python library with that specific version of blender. Could I ask, how did you install blender? (e.g. running it from a .zip, or using the windows installer; and whether you selected 32bit versus 64 bit).

While I can't prevent all cases of a bad python library, I can at least take this into consideration and make improvements to the addon where you would at least be able to use some functionality. I'll see if I can address it to make it fail safe better.

**Comment by CrazyLevi** [comment]
I innstalled blender via the website and the innstaller. I use a 64 bit computer so I use 64 bit blender

**Comment by TheDuckCow** [comment]
Okay thanks for the information. Again, the issue stems from a bad install. I’d suggest in the meantime trying to run blender from the .zip (instead of using the installer) or even try installing blender 2.78 (again try running it from the self contained .zip). The issue with your current blender install is in a python library which isn’t that commonly used, but is used inside MCprep which is why most other things probably seem to work fine.

**Comment by CrazyLevi** [comment]
Ok! Thanks!
