### ISSUE TITLE
something wrong with saving and particles

### ISSUE THREAD

**Issue by Flapek122** [TheDuckCow/MCprep#441]
### Name of asset submission

![image](https://github.com/TheDuckCow/MCprep/assets/138986133/bb3dddee-6b39-4e93-8ff9-9be1031c9e1c)

### Quality checks

- [X] I have used only vanilla textures (or created images that are derived from vanilla textures)
- [X] This is a vanilla minecraft asset/mob/effect
- [X] I have verified my asset has the correct scale (1 Blender unit = 1 meter), and the scale has been applied (control+a, scale)
- [X] If my asset includes a rig, I certified there is a "root" or "main" bone, and the rig object name ends with the name ".arma" or ".rig" to work well with MCprep
- [X] I am the sole creator of this rig, other than any textures by Mojang. Any custom textures I created myself.

### Confirmation

- [X] By submitting this asset, I affirm the asset is of my own creation. I understand this asset will be included with MCprep with a CC-BY (attribution) license agreement, and that users of MCprep should refer to [MCprep's readme](https://github.com/TheDuckCow/MCprep#credit) for credit or directly name me for credit when this rig is used.

**Comment by TheDuckCow** [comment]
Looks like your textures got disconnected. This is more of a behavior of blender itself than anything specific to the addon, this could happen if you moved a blend file into another folder while using relative paths, or if you cleared textures inside the default MCprep location.

If nothing appears to be missing in your scene, try using the file > find missing and then point it to the MCprep addon folder. Or, try re-installing MCprep if your textures are indeed missing.

<img width="486" alt="Screen Shot 2023-07-08 at 10 43 59 AM" src="https://github.com/TheDuckCow/MCprep/assets/2958461/e12709fc-7957-4d34-8cbc-42eb42ea6d15">

As a side note, we are dropping 2.7 support in the next version, so there won't be other updates coming out for 2.7x. https://github.com/TheDuckCow/MCprep/issues/399

I'm closing the issue mostly due to this last point, but let us know if the tips above resolve your problem.
