### ISSUE TITLE
Add icon for the block (model) looks like other items

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [TheDuckCow/MCprep#444]
### Check against existing requests

- [X] I have checked existing feature requests, and my idea is different

### Describe the context

May be you have forgotten to add icon for them? (Or have some reason that can't do this right now)

Add icon for the block(model)
![image](https://github.com/TheDuckCow/MCprep/assets/65578116/fb4f6112-f595-4472-acef-2aefd8568244)

### How do you imagine your feature works?

Not hard.
![image](https://github.com/TheDuckCow/MCprep/assets/65578116/410a876a-c428-4f53-b29e-4188f3e9e5ce)

### What existing workaround (or closest thing to a workaround) do you have today (within Blender, MCprep, or any software)? If there is no workaround, explain why you feel this way.

just add it

**Comment by zNightlord** [comment]
Rather think as the concept is "not hard", think as why it isn't consistent in the first place.
As like mobs we only have like 20, 30 16 pixels images. For the blocks their count is around 1000

So you have to iterate atleast 1000 times, 
reading through the json file to get the texture path (should I count some block has different side texture, what should we pick "top" "north" "bottom"... to get the correct display texture) 
and python is...

**Comment by zNightlord** [comment]
If you interested in having previews, #414 is something you might want to check

**Comment by BUGProtectionAssociation** [comment]
> Rather think as the concept is "not hard", think as why it isn't consistent in the first place. As like mobs we only have like 20, 30 16 pixels images. For the blocks their count is around 1000
> 
> So you have to iterate atleast 1000 times, reading through the json file to get the texture path (should I count some block has different side texture, what should we pick "top" "north" "bottom"... to get the correct display texture) and python is...

So..it will be slow...I konw
But why them not has icon too
![image](https://github.com/TheDuckCow/MCprep/assets/65578116/c202d105-ead3-4926-963a-0da3b4968a2e)

**Comment by zNightlord** [comment]
> So..it will be slow...I konw But why them not has icon too ![image](https://user-images.githubusercontent.com/65578116/252200513-c202d105-ead3-4926-963a-0da3b4968a2e.png)

Good question.
They are dynamically change based on your files. If you add more mob rigs, add more blocks in meshswap or entities those won't have preview.

I am not really sure why only the default builtin mobs have previews/icons in the first place myself.

**Comment by zNightlord** [comment]
I guess you can answer that for me if you start looking around in the rigs folder, it is somewhere in that

**Comment by StandingPadAnimations** [comment]
Commenting on this issue since I feel the current answer is over-complicated. I'll close this issue as not planned, but you'll still be able to comment

_Short answer_: it's too low of a priority for us compared to the major stuff that we MCprep developers have to work on (including bugs that slip past, the current release was actually primarily to fix a major bug that we didn't catch in development) 

_Long answer_: In addition to priority, those panels don't have icons is because way they're loaded is different compared to mobs (dynamically rather then a predefined list):
- Meshswap objects and entity rigs are retrieved from meshswap and entity blend files (although entities we might be able to add icons though, it's a low priority)
- JSON models are loaded based on what JSON files are found for the current resource pack 

Those files don't have images associated with them, mostly because either there's no good way (like with multiple objects in single blend files) or there's too many of them (like JSON models). For just JSON models alone, assuming every resource pack ever is updated to the latest version, we would need 820 images for each block, which adds up. MCprep is already pretty massive, and adding 820 images would make it way, way more massive to the point where download speeds would be severely affected.

Mobs meanwhile are basically hardcoded, since they're based on what's submitted to us. It's not like blocks which are dynamically updated based on resource pack and whatnot, they're mostly predefined based on what is submitted to us.

It mainly goes back to the differences in how those panels are loaded and the fact that having icons for every single block in Minecraft would negatively impact MCprep's size.
