### ISSUE TITLE
Blender 2.8 Support

### ISSUE THREAD

**Issue by aaadell** [TheDuckCow/MCprep#60]
[Original title: does MCprep 3.1.1 work with blender 2.8 beta ?]

i tried to many times to enable MCprep 3.1.1 with blender 2.8 
but it doesn't work 
give me this issue
[url=https://up.top4top.net/][img]https://e.top4top.net/p_1069u36gl1.png[/img][/url]

**Comment by TheDuckCow** [comment]
MCprep does not yet support blender 2.8, a good majority of the addon needs rewriting first. I am planning a 2.8 version release in the near future with more limited features, but until then use blender 2.8. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment]
Hey there, I just wanted to call out that I am working on this and [making good progress](https://twitter.com/TheDuckCow/status/1102272235837014017). Still no ETA, but... should not be that far of, still a few things I need to work out.

**Comment by Somfic** [comment]
Do you have an ETA yet?

**Comment by TheDuckCow** [comment]
It’s pretty close, there’s some features that need to be cleaned up a bit. It maybe be another week or two (hopefully at most). 

However, feel free to try out this interim build:
https://forms.gle/zY8HJb6tBAuKHDGP7

It has some bugs still that I’ve since fixed, but still should meet many of your immediate Blender 2.8 needs. Still report any bugs if you encounter them!

Patrick

**Comment by TheDuckCow** [comment]
Closing this issue as 2.8 support has finally, and officially, been released!
