### ISSUE TITLE
Grass bright green

### ISSUE THREAD

**Issue by SorcererAssassin** [TheDuckCow/MCprep#635]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Whenever I import a world, the grass looks bright green. Prep materials doesn't seem to help. Maybe it's an issue with jmc2obj, but I have yet to get an answer from their side.
![Schermafbeelding 2024-09-21 092919](https://github.com/user-attachments/assets/f2b8afb9-7b1b-40fa-8124-767936178790)

I tried everything: older version of Blender, mcprep and jmc2obj. I uninstalled and reinstalled blender. I reverted back to factory settings.

### What steps are needed to produce the bug?

I honestly don't know how others can recreate this issue. I don't know if it happened after updating mcprep or if it's the latest version of jmc2obj.

### What version of MCprep are you using?

The latest: v3.6.1.2

### What version of Blender are you using?

The latest: v4.2.0

**Comment by TheDuckCow** [comment]
In Minecraft, the grass color is actually grayscale so that biomes can control the color and transition of shades between areas. With jmc2obj and Mineways, there's no real good way to export out this procedural-based definition of shading, hence they just export a generic representative green.

In MCprep, if you want to really have a custom or event biome-procedural texture, you can certainly do so by customizing the material itself. Simplest way would be to go into the material after pressing prep materials, and then insert an HSL node and/or brightness/contrast node. Or, if you use "swap texturepack" with the base texture pack, you'll get the actual source grayscale image (where you can then adjust the provided add color node which adds color back on top).

And then, if you want to save this material for future reuse, then you can append it into the [sync materials](https://github.com/Moo-Ack-Productions/MCprep?tab=readme-ov-file#sync-materials) blend file; then on future "prep materials" (if you make sure "sync materials" is ticked) it'll pull in this custom material instead of the default one, just be careful whenever updating your MCprep addon / consider saving it in a new location.

Going to close this, since this is a mostly fundamental situation that we can't really change. Hope the above steps help.
