### ISSUE TITLE
Hello theduckcow

### ISSUE THREAD

**Issue by MCPANDAGAMES** [TheDuckCow/MCprep#64]
I have been having problems spawning weapons and I'm in blender 2.79 I've tried installing and uninstalling many times but it still gives me this error
![image](https://user-images.githubusercontent.com/47498399/52534039-3b6c1880-2d34-11e9-914d-2bb078b8ca0a.png)
and its really bugging me please tell me how to fix it, it would be greatly appreciated.
From thepandagames.

**Comment by TheDuckCow** [comment]
Hey there,

It seems there is a deeper level issue with he blender python library. Can you tell me how you installed blender (ie the windows installer, or if it is running from a zip file); and if not running from an unzipped zip file, can you try that and see if it works? This is an error due to mcprep depending on a python library that should exist but is for some reason broken for you. 


Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment]
Just a follow up on this, could you let me know based on my previous message? Thanks!

**Comment by MCPANDAGAMES** [comment]
hey there I'm using a rig with this and honestly when I spawn with a rig it shows this error.
if I have no rigs open it works I don't know whats happening here.
I'm using zanimations rig
![image](https://user-images.githubusercontent.com/47498399/53038154-ea66cd80-3473-11e9-966d-b69e1597da6d.png)And after the error message it just makes a white planes thx tho.

**Comment by TheDuckCow** [comment]
Following up on this, can you see if the issue persists in the latest 3.2.0 release of MCprep? Be sure to install, then completely close Blender, and re-open to test it out.

**Comment by TheDuckCow** [comment]
Marking this as solved for now, as I'm fairly sure the new update addresses this issue. Comment back if this is not the case.
