### ISSUE TITLE
using Mcprep changes viewport sharing to texture

### ISSUE THREAD

**Issue by Zophiekat** [TheDuckCow/MCprep#66]
is there a reason why using any mcprep action changes your viewport's shading to texture? i usually work in material view, although this didnt happen in the previous version of mcprep soooo.... is this a bug or a performance feature? 🤔

**Comment by TheDuckCow** [comment]
Hello,

I was getting a ton of “bug reports” saying prep materials wasn’t doing anything, when in reality it was working but those individuals just weren’t seeing any changes in the viewport. Thus, I changed the default to have the “Improve UI” option enabled. More recently than that, I made it so that this Improve UI button/option be that, if Cycles was enabled, it would make the minimum draw Textured mode. This is because in my experience, the option to show textures in solid mode was not working for cycles, and I wanted to make sure that textures were showing so that users would see the results directly in the viewport. 

For your use case, I would just turn *off* the “Improve UI” setting when prepping materials.



Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com <https://theduckcow.com/>
youtube <http://www.youtube.com/TheDuckCow>, twitter <https://twitter.com/TheDuckCow>, facebook <https://www.facebook.com/TheDuckCow>
