### ISSUE TITLE
How make lighting blocks act like lights?

### ISSUE THREAD

**Issue by Somfic** [TheDuckCow/MCprep#80]
Hi, I'm looking for a way to have torches behave like actual lights, that are able to cast shadows, etc. I'm new to blender so maybe there's an easy way that I'm not seeing?

**Comment by Danielv123** [comment]
Change the material at the top of the torch to be emissive.

**Comment by Somfic** [comment]
Those don't cast shadows though

**Comment by Danielv123** [comment]
All objects in blender cycles cast shadows as you would expect them to.

**Comment by TheDuckCow** [comment]
Hi @Somfic I think I know what you are referring to. Firstly, depends on your render engine - if using cycles, then yes, making the material emmisive will make the torch's fire mesh object emit light such that other objects will cast shadows from that light. If you are using Blender Internal or Eevee, then your best bet is to actually place an actual point light in the fir block, and then make this fire object be invisible to the lamp (ie so that it doesn't cast a shadow itself). 

If looking for a reference, if I recall correctly, this is how I create the torch meshswap group work. Try using that as a reference.

**Comment by TheDuckCow** [comment]
Closing this for now (as this is more of a blender usage detail than MCprep specifically), feel free to comment back if you want more help though.
