### ISSUE TITLE
Swap Texture Pack doesn't work [Mineways]

### ISSUE THREAD

**Issue by TheEA66** [TheDuckCow/MCprep#95]
When I swap the texture pack, this happens. I tried two texture packs
![image](https://user-images.githubusercontent.com/58154226/69504980-a5813300-0eec-11ea-9bde-55845ce5416e.png)

**Comment by TheDuckCow** [comment]
Hi there, sorry you are having trouble. A few questions to help troubleshoot:

- What is the origin of the block/world imported (jmc2obj?)? Or did you make/texture this block yourself
- How does it look in rendered view? It could be artifacts of the viewport if your texturepack has spec/normal maps as well.
- Can you share a screenshot of "before"
- Can you share the UV layout of this block? Just screenshot the editor with all faces selected.

**Comment by TheEA66** [comment]
Hi, I hope It's OK if I just recorded a video. I think I did something
wrong when I swapped the texture pack. I followed the swapping tutorial
though

**Comment by TheDuckCow** [comment]
Yup video is even better, this is perfect. I know the issue exactly, it's because of UV mapping - specifically, you are starting with a setup where all textures are combined as one image, but swap texture pack expects that each texture is its own image.

Generally, support for Mineways (I think that's what you are using) is coming but not ready yet. Note that even when it is ready, you'll have to use one of the newer options called "Export tiles for texture to directory" which will make one image file per texture individually (similar to how modern day Minecraft Resource Packs work, which is the way texture swap was designed). Again, not ready yet for Mineways, but coming.

**Comment by TheEA66** [comment]
Thank you for your reply!

**Comment by TheEA66** [comment]
Again, Thank you, It worked

**Comment by erich666** [comment]
Is some feature needed in Mineways itself? Let me know.

**Comment by TheDuckCow** [comment]
Hi @erich666, I think it's all good! The holdup at this stage is on my end, I still need to get that manual mapping of materials from the source code for both Mineways and jmc2obj sorted out, and I've just been putting it off.
